//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JubatusAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categories
    {
        public int CategorieId { get; set; }
        public string CategorieName { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreateTime { get; set; }
        public bool IsEnabled { get; set; }
    }
}
