//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JubatusAdmin.Models
{
    public partial class Member
    {
        public int MemberId { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public int MemberRoleId { get; set; }
        public int IsActive { get; set; }
    }
}
